/*
Hivelocity API

Interact with Hivelocity

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// SshKeyUpdate struct for SshKeyUpdate
type SshKeyUpdate struct {
	Name      *string `json:"name,omitempty"`
	PublicKey *string `json:"publicKey,omitempty"`
}

// NewSshKeyUpdate instantiates a new SshKeyUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSshKeyUpdate() *SshKeyUpdate {
	this := SshKeyUpdate{}
	return &this
}

// NewSshKeyUpdateWithDefaults instantiates a new SshKeyUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSshKeyUpdateWithDefaults() *SshKeyUpdate {
	this := SshKeyUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SshKeyUpdate) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SshKeyUpdate) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SshKeyUpdate) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SshKeyUpdate) SetName(v string) {
	o.Name = &v
}

// GetPublicKey returns the PublicKey field value if set, zero value otherwise.
func (o *SshKeyUpdate) GetPublicKey() string {
	if o == nil || isNil(o.PublicKey) {
		var ret string
		return ret
	}
	return *o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SshKeyUpdate) GetPublicKeyOk() (*string, bool) {
	if o == nil || isNil(o.PublicKey) {
		return nil, false
	}
	return o.PublicKey, true
}

// HasPublicKey returns a boolean if a field has been set.
func (o *SshKeyUpdate) HasPublicKey() bool {
	if o != nil && !isNil(o.PublicKey) {
		return true
	}

	return false
}

// SetPublicKey gets a reference to the given string and assigns it to the PublicKey field.
func (o *SshKeyUpdate) SetPublicKey(v string) {
	o.PublicKey = &v
}

func (o SshKeyUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.PublicKey) {
		toSerialize["publicKey"] = o.PublicKey
	}
	return json.Marshal(toSerialize)
}

type NullableSshKeyUpdate struct {
	value *SshKeyUpdate
	isSet bool
}

func (v NullableSshKeyUpdate) Get() *SshKeyUpdate {
	return v.value
}

func (v *NullableSshKeyUpdate) Set(val *SshKeyUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSshKeyUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSshKeyUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSshKeyUpdate(val *SshKeyUpdate) *NullableSshKeyUpdate {
	return &NullableSshKeyUpdate{value: val, isSet: true}
}

func (v NullableSshKeyUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSshKeyUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
