/*
Hivelocity API

Interact with Hivelocity

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// TicketPut struct for TicketPut
type TicketPut struct {
	Status *string `json:"status,omitempty"`
}

// NewTicketPut instantiates a new TicketPut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTicketPut() *TicketPut {
	this := TicketPut{}
	return &this
}

// NewTicketPutWithDefaults instantiates a new TicketPut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTicketPutWithDefaults() *TicketPut {
	this := TicketPut{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TicketPut) GetStatus() string {
	if o == nil || isNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TicketPut) GetStatusOk() (*string, bool) {
	if o == nil || isNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TicketPut) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TicketPut) SetStatus(v string) {
	o.Status = &v
}

func (o TicketPut) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableTicketPut struct {
	value *TicketPut
	isSet bool
}

func (v NullableTicketPut) Get() *TicketPut {
	return v.value
}

func (v *NullableTicketPut) Set(val *TicketPut) {
	v.value = val
	v.isSet = true
}

func (v NullableTicketPut) IsSet() bool {
	return v.isSet
}

func (v *NullableTicketPut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTicketPut(val *TicketPut) *NullableTicketPut {
	return &NullableTicketPut{value: val, isSet: true}
}

func (v NullableTicketPut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTicketPut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
