/*
Hivelocity API

Interact with Hivelocity

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// DeploymentStart struct for DeploymentStart
type DeploymentStart struct {
	Script      *string `json:"script,omitempty"`
	BillingInfo int32   `json:"billingInfo"`
}

// NewDeploymentStart instantiates a new DeploymentStart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentStart(billingInfo int32) *DeploymentStart {
	this := DeploymentStart{}
	this.BillingInfo = billingInfo
	return &this
}

// NewDeploymentStartWithDefaults instantiates a new DeploymentStart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentStartWithDefaults() *DeploymentStart {
	this := DeploymentStart{}
	return &this
}

// GetScript returns the Script field value if set, zero value otherwise.
func (o *DeploymentStart) GetScript() string {
	if o == nil || isNil(o.Script) {
		var ret string
		return ret
	}
	return *o.Script
}

// GetScriptOk returns a tuple with the Script field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentStart) GetScriptOk() (*string, bool) {
	if o == nil || isNil(o.Script) {
		return nil, false
	}
	return o.Script, true
}

// HasScript returns a boolean if a field has been set.
func (o *DeploymentStart) HasScript() bool {
	if o != nil && !isNil(o.Script) {
		return true
	}

	return false
}

// SetScript gets a reference to the given string and assigns it to the Script field.
func (o *DeploymentStart) SetScript(v string) {
	o.Script = &v
}

// GetBillingInfo returns the BillingInfo field value
func (o *DeploymentStart) GetBillingInfo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BillingInfo
}

// GetBillingInfoOk returns a tuple with the BillingInfo field value
// and a boolean to check if the value has been set.
func (o *DeploymentStart) GetBillingInfoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingInfo, true
}

// SetBillingInfo sets field value
func (o *DeploymentStart) SetBillingInfo(v int32) {
	o.BillingInfo = v
}

func (o DeploymentStart) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Script) {
		toSerialize["script"] = o.Script
	}
	if true {
		toSerialize["billingInfo"] = o.BillingInfo
	}
	return json.Marshal(toSerialize)
}

type NullableDeploymentStart struct {
	value *DeploymentStart
	isSet bool
}

func (v NullableDeploymentStart) Get() *DeploymentStart {
	return v.value
}

func (v *NullableDeploymentStart) Set(val *DeploymentStart) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentStart) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentStart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentStart(val *DeploymentStart) *NullableDeploymentStart {
	return &NullableDeploymentStart{value: val, isSet: true}
}

func (v NullableDeploymentStart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentStart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
