/*
Hivelocity API

Interact with Hivelocity

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// DeploymentCustomization struct for DeploymentCustomization
type DeploymentCustomization struct {
	Quantity *int32 `json:"quantity,omitempty"`
	// must be one of ['monthly', 'quarterly', 'semi-annually', 'annually', 'biennial', 'triennial', 'hourly']
	BillingPeriod *string `json:"billingPeriod,omitempty"`
	LocationCode  *string `json:"locationCode,omitempty"`
	// URL to download custom iPXE script if not supplying script in entirety
	CustomIPXEScriptURL *string `json:"customIPXEScriptURL,omitempty"`
	// ID of SSH Key to use for deployment
	PublicSshKeyId  *int32   `json:"publicSshKeyId,omitempty"`
	AdditionalNotes []string `json:"additionalNotes,omitempty"`
	Options         []int32  `json:"options,omitempty"`
	// Either deploy these Device IDs or fail
	ForceDeviceIds []int32  `json:"forceDeviceIds,omitempty"`
	Hostnames      []string `json:"hostnames"`
	// Operating System's Name or ID
	OperatingSystem string `json:"operatingSystem"`
	// Specify Ignition file ID for CoreOS/Flatcar provisions
	IgnitionIds []int32 `json:"ignitionIds,omitempty"`
	ProductId   int32   `json:"productId"`
	// Contents of iPXE script if not supplying URL
	CustomIPXEScriptContents *string `json:"customIPXEScriptContents,omitempty"`
}

// NewDeploymentCustomization instantiates a new DeploymentCustomization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentCustomization(hostnames []string, operatingSystem string, productId int32) *DeploymentCustomization {
	this := DeploymentCustomization{}
	var billingPeriod string = "monthly"
	this.BillingPeriod = &billingPeriod
	var locationCode string = ""
	this.LocationCode = &locationCode
	this.Hostnames = hostnames
	this.OperatingSystem = operatingSystem
	this.ProductId = productId
	return &this
}

// NewDeploymentCustomizationWithDefaults instantiates a new DeploymentCustomization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentCustomizationWithDefaults() *DeploymentCustomization {
	this := DeploymentCustomization{}
	var billingPeriod string = "monthly"
	this.BillingPeriod = &billingPeriod
	var locationCode string = ""
	this.LocationCode = &locationCode
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetQuantity() int32 {
	if o == nil || isNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetQuantityOk() (*int32, bool) {
	if o == nil || isNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasQuantity() bool {
	if o != nil && !isNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *DeploymentCustomization) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetBillingPeriod returns the BillingPeriod field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetBillingPeriod() string {
	if o == nil || isNil(o.BillingPeriod) {
		var ret string
		return ret
	}
	return *o.BillingPeriod
}

// GetBillingPeriodOk returns a tuple with the BillingPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetBillingPeriodOk() (*string, bool) {
	if o == nil || isNil(o.BillingPeriod) {
		return nil, false
	}
	return o.BillingPeriod, true
}

// HasBillingPeriod returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasBillingPeriod() bool {
	if o != nil && !isNil(o.BillingPeriod) {
		return true
	}

	return false
}

// SetBillingPeriod gets a reference to the given string and assigns it to the BillingPeriod field.
func (o *DeploymentCustomization) SetBillingPeriod(v string) {
	o.BillingPeriod = &v
}

// GetLocationCode returns the LocationCode field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetLocationCode() string {
	if o == nil || isNil(o.LocationCode) {
		var ret string
		return ret
	}
	return *o.LocationCode
}

// GetLocationCodeOk returns a tuple with the LocationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetLocationCodeOk() (*string, bool) {
	if o == nil || isNil(o.LocationCode) {
		return nil, false
	}
	return o.LocationCode, true
}

// HasLocationCode returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasLocationCode() bool {
	if o != nil && !isNil(o.LocationCode) {
		return true
	}

	return false
}

// SetLocationCode gets a reference to the given string and assigns it to the LocationCode field.
func (o *DeploymentCustomization) SetLocationCode(v string) {
	o.LocationCode = &v
}

// GetCustomIPXEScriptURL returns the CustomIPXEScriptURL field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetCustomIPXEScriptURL() string {
	if o == nil || isNil(o.CustomIPXEScriptURL) {
		var ret string
		return ret
	}
	return *o.CustomIPXEScriptURL
}

// GetCustomIPXEScriptURLOk returns a tuple with the CustomIPXEScriptURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetCustomIPXEScriptURLOk() (*string, bool) {
	if o == nil || isNil(o.CustomIPXEScriptURL) {
		return nil, false
	}
	return o.CustomIPXEScriptURL, true
}

// HasCustomIPXEScriptURL returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasCustomIPXEScriptURL() bool {
	if o != nil && !isNil(o.CustomIPXEScriptURL) {
		return true
	}

	return false
}

// SetCustomIPXEScriptURL gets a reference to the given string and assigns it to the CustomIPXEScriptURL field.
func (o *DeploymentCustomization) SetCustomIPXEScriptURL(v string) {
	o.CustomIPXEScriptURL = &v
}

// GetPublicSshKeyId returns the PublicSshKeyId field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetPublicSshKeyId() int32 {
	if o == nil || isNil(o.PublicSshKeyId) {
		var ret int32
		return ret
	}
	return *o.PublicSshKeyId
}

// GetPublicSshKeyIdOk returns a tuple with the PublicSshKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetPublicSshKeyIdOk() (*int32, bool) {
	if o == nil || isNil(o.PublicSshKeyId) {
		return nil, false
	}
	return o.PublicSshKeyId, true
}

// HasPublicSshKeyId returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasPublicSshKeyId() bool {
	if o != nil && !isNil(o.PublicSshKeyId) {
		return true
	}

	return false
}

// SetPublicSshKeyId gets a reference to the given int32 and assigns it to the PublicSshKeyId field.
func (o *DeploymentCustomization) SetPublicSshKeyId(v int32) {
	o.PublicSshKeyId = &v
}

// GetAdditionalNotes returns the AdditionalNotes field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetAdditionalNotes() []string {
	if o == nil || isNil(o.AdditionalNotes) {
		var ret []string
		return ret
	}
	return o.AdditionalNotes
}

// GetAdditionalNotesOk returns a tuple with the AdditionalNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetAdditionalNotesOk() ([]string, bool) {
	if o == nil || isNil(o.AdditionalNotes) {
		return nil, false
	}
	return o.AdditionalNotes, true
}

// HasAdditionalNotes returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasAdditionalNotes() bool {
	if o != nil && !isNil(o.AdditionalNotes) {
		return true
	}

	return false
}

// SetAdditionalNotes gets a reference to the given []string and assigns it to the AdditionalNotes field.
func (o *DeploymentCustomization) SetAdditionalNotes(v []string) {
	o.AdditionalNotes = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetOptions() []int32 {
	if o == nil || isNil(o.Options) {
		var ret []int32
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetOptionsOk() ([]int32, bool) {
	if o == nil || isNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasOptions() bool {
	if o != nil && !isNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []int32 and assigns it to the Options field.
func (o *DeploymentCustomization) SetOptions(v []int32) {
	o.Options = v
}

// GetForceDeviceIds returns the ForceDeviceIds field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetForceDeviceIds() []int32 {
	if o == nil || isNil(o.ForceDeviceIds) {
		var ret []int32
		return ret
	}
	return o.ForceDeviceIds
}

// GetForceDeviceIdsOk returns a tuple with the ForceDeviceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetForceDeviceIdsOk() ([]int32, bool) {
	if o == nil || isNil(o.ForceDeviceIds) {
		return nil, false
	}
	return o.ForceDeviceIds, true
}

// HasForceDeviceIds returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasForceDeviceIds() bool {
	if o != nil && !isNil(o.ForceDeviceIds) {
		return true
	}

	return false
}

// SetForceDeviceIds gets a reference to the given []int32 and assigns it to the ForceDeviceIds field.
func (o *DeploymentCustomization) SetForceDeviceIds(v []int32) {
	o.ForceDeviceIds = v
}

// GetHostnames returns the Hostnames field value
func (o *DeploymentCustomization) GetHostnames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Hostnames
}

// GetHostnamesOk returns a tuple with the Hostnames field value
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetHostnamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hostnames, true
}

// SetHostnames sets field value
func (o *DeploymentCustomization) SetHostnames(v []string) {
	o.Hostnames = v
}

// GetOperatingSystem returns the OperatingSystem field value
func (o *DeploymentCustomization) GetOperatingSystem() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperatingSystem
}

// GetOperatingSystemOk returns a tuple with the OperatingSystem field value
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetOperatingSystemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperatingSystem, true
}

// SetOperatingSystem sets field value
func (o *DeploymentCustomization) SetOperatingSystem(v string) {
	o.OperatingSystem = v
}

// GetIgnitionIds returns the IgnitionIds field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetIgnitionIds() []int32 {
	if o == nil || isNil(o.IgnitionIds) {
		var ret []int32
		return ret
	}
	return o.IgnitionIds
}

// GetIgnitionIdsOk returns a tuple with the IgnitionIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetIgnitionIdsOk() ([]int32, bool) {
	if o == nil || isNil(o.IgnitionIds) {
		return nil, false
	}
	return o.IgnitionIds, true
}

// HasIgnitionIds returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasIgnitionIds() bool {
	if o != nil && !isNil(o.IgnitionIds) {
		return true
	}

	return false
}

// SetIgnitionIds gets a reference to the given []int32 and assigns it to the IgnitionIds field.
func (o *DeploymentCustomization) SetIgnitionIds(v []int32) {
	o.IgnitionIds = v
}

// GetProductId returns the ProductId field value
func (o *DeploymentCustomization) GetProductId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetProductIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *DeploymentCustomization) SetProductId(v int32) {
	o.ProductId = v
}

// GetCustomIPXEScriptContents returns the CustomIPXEScriptContents field value if set, zero value otherwise.
func (o *DeploymentCustomization) GetCustomIPXEScriptContents() string {
	if o == nil || isNil(o.CustomIPXEScriptContents) {
		var ret string
		return ret
	}
	return *o.CustomIPXEScriptContents
}

// GetCustomIPXEScriptContentsOk returns a tuple with the CustomIPXEScriptContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCustomization) GetCustomIPXEScriptContentsOk() (*string, bool) {
	if o == nil || isNil(o.CustomIPXEScriptContents) {
		return nil, false
	}
	return o.CustomIPXEScriptContents, true
}

// HasCustomIPXEScriptContents returns a boolean if a field has been set.
func (o *DeploymentCustomization) HasCustomIPXEScriptContents() bool {
	if o != nil && !isNil(o.CustomIPXEScriptContents) {
		return true
	}

	return false
}

// SetCustomIPXEScriptContents gets a reference to the given string and assigns it to the CustomIPXEScriptContents field.
func (o *DeploymentCustomization) SetCustomIPXEScriptContents(v string) {
	o.CustomIPXEScriptContents = &v
}

func (o DeploymentCustomization) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !isNil(o.BillingPeriod) {
		toSerialize["billingPeriod"] = o.BillingPeriod
	}
	if !isNil(o.LocationCode) {
		toSerialize["locationCode"] = o.LocationCode
	}
	if !isNil(o.CustomIPXEScriptURL) {
		toSerialize["customIPXEScriptURL"] = o.CustomIPXEScriptURL
	}
	if !isNil(o.PublicSshKeyId) {
		toSerialize["publicSshKeyId"] = o.PublicSshKeyId
	}
	if !isNil(o.AdditionalNotes) {
		toSerialize["additionalNotes"] = o.AdditionalNotes
	}
	if !isNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	if !isNil(o.ForceDeviceIds) {
		toSerialize["forceDeviceIds"] = o.ForceDeviceIds
	}
	if true {
		toSerialize["hostnames"] = o.Hostnames
	}
	if true {
		toSerialize["operatingSystem"] = o.OperatingSystem
	}
	if !isNil(o.IgnitionIds) {
		toSerialize["ignitionIds"] = o.IgnitionIds
	}
	if true {
		toSerialize["productId"] = o.ProductId
	}
	if !isNil(o.CustomIPXEScriptContents) {
		toSerialize["customIPXEScriptContents"] = o.CustomIPXEScriptContents
	}
	return json.Marshal(toSerialize)
}

type NullableDeploymentCustomization struct {
	value *DeploymentCustomization
	isSet bool
}

func (v NullableDeploymentCustomization) Get() *DeploymentCustomization {
	return v.value
}

func (v *NullableDeploymentCustomization) Set(val *DeploymentCustomization) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentCustomization) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentCustomization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentCustomization(val *DeploymentCustomization) *NullableDeploymentCustomization {
	return &NullableDeploymentCustomization{value: val, isSet: true}
}

func (v NullableDeploymentCustomization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentCustomization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
