/*
Hivelocity API

Interact with Hivelocity

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// WebhookUpdate struct for WebhookUpdate
type WebhookUpdate struct {
	Name    *string                `json:"name,omitempty"`
	Event   *string                `json:"event,omitempty"`
	Url     *string                `json:"url,omitempty"`
	Headers map[string]interface{} `json:"headers,omitempty"`
}

// NewWebhookUpdate instantiates a new WebhookUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookUpdate() *WebhookUpdate {
	this := WebhookUpdate{}
	return &this
}

// NewWebhookUpdateWithDefaults instantiates a new WebhookUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookUpdateWithDefaults() *WebhookUpdate {
	this := WebhookUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WebhookUpdate) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdate) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WebhookUpdate) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WebhookUpdate) SetName(v string) {
	o.Name = &v
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *WebhookUpdate) GetEvent() string {
	if o == nil || isNil(o.Event) {
		var ret string
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdate) GetEventOk() (*string, bool) {
	if o == nil || isNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *WebhookUpdate) HasEvent() bool {
	if o != nil && !isNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given string and assigns it to the Event field.
func (o *WebhookUpdate) SetEvent(v string) {
	o.Event = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *WebhookUpdate) GetUrl() string {
	if o == nil || isNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdate) GetUrlOk() (*string, bool) {
	if o == nil || isNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *WebhookUpdate) HasUrl() bool {
	if o != nil && !isNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *WebhookUpdate) SetUrl(v string) {
	o.Url = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *WebhookUpdate) GetHeaders() map[string]interface{} {
	if o == nil || isNil(o.Headers) {
		var ret map[string]interface{}
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdate) GetHeadersOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Headers) {
		return map[string]interface{}{}, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *WebhookUpdate) HasHeaders() bool {
	if o != nil && !isNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]interface{} and assigns it to the Headers field.
func (o *WebhookUpdate) SetHeaders(v map[string]interface{}) {
	o.Headers = v
}

func (o WebhookUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !isNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !isNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	return json.Marshal(toSerialize)
}

type NullableWebhookUpdate struct {
	value *WebhookUpdate
	isSet bool
}

func (v NullableWebhookUpdate) Get() *WebhookUpdate {
	return v.value
}

func (v *NullableWebhookUpdate) Set(val *WebhookUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookUpdate(val *WebhookUpdate) *NullableWebhookUpdate {
	return &NullableWebhookUpdate{value: val, isSet: true}
}

func (v NullableWebhookUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
